### ISSUE TITLE
Kick from server when picking up rug

### ISSUE THREAD

**Issue by RiskyKen** [kihira/PlayerRugs#5]
Don't know if you are still updating for 1.7.10 but I thought I would post this anyway.

When playing on a dedicated server players will be kicked from the server when they harvest a rug. The following error shows in the server console when it happens.

http://pastebin.com/MvBwff7C

The client is able to reconnect fine and the item will be on the ground waiting for them. If there is mutable players around only the player that harvested the rug is effected.

Forge: 1.7.10-10.13.4.1566
PlayerRugs: 1.7.10-1.1.2

**Comment by kihira** [comment]
Completely forgot about this, woops.

Dropping support for 1.7.10 anyway
